services:
  - type: web
    name: disaster-api
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt && python data/generate_synthetic_data.py && python app/ml/train_model.py"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: SEED_DB
        value: "true"
      - key: CORS_ORIGINS
        value: "*" # Allowing all origins for the hackathon demo to ensure frontend connects

  - type: web
    name: disaster-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build && npm install -g serve"
    startCommand: "serve -s frontend/dist -l $PORT"
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: VITE_API_URL
        fromService:
          type: web
          name: disaster-api
          envVarKey: RENDER_EXTERNAL_URL
